const QuizQuestions = [
    {
        id: 1,
        question: 
        // eslint-disable-next-line max-len
        'If you stand on a rock and throw a rubber duck 8 meters, and then step down and throw the duck again, how far will it go?',
        answerOne: '12 meters, of course',
        answerTwo: 'Fel svar2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 2,
        question: 'The very first rubber ducks were made in late 1800. What couldn´t they do?',
        answerOne: 'Sink',
        answerTwo: 'Be chewed on',
        correctAnswer: 'Float',
    },
    {
        id: 3,
        question: 
        // eslint-disable-next-line max-len
        'Lizzy the duck was faster than Bob the duck at swimming. Bob was faster than Lizzy at flying. Lizzy was yellower than Bob. What color is Bob?',
        answerOne: 'Fel svar 1',
        answerTwo: 'Fel svar 2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 4,
        question: 'How does a rubber duck spend its weekends?',
        answerOne: 'Fel svar 1',
        answerTwo: 'Fel svar 2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 5,
        question: 'Which of the following have rubber ducks been used to measure?',
        answerOne: 'Rubber ducks have been employed to study the migratory patterns of deep-sea creatures.',
        answerTwo: 'Rubber ducks have been utilized to map underwater geological features and topography. ',
        correctAnswer: 'Rubber ducks have been used to measure ocean currents. ',
    },
    {
        id: 6,
        question: 'How many duck fits in a bathtub',
        answerOne: 'Fel svar1',
        answerTwo: 'Fel svar2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 7,
        question: 'How many duck fits in a bathtub',
        answerOne: 'Fel svar 1',
        answerTwo: 'Fel svar 2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 8,
        question: 'How many duck fits in a bathtub',
        answerOne: 'Fel svar 1',
        answerTwo: 'Fel svar 2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 9,
        question: 'How many duck fits in a bathtub',
        answerOne: 'Fel svar 1',
        answerTwo: 'Fel svar 2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 10,
        question: 'How many duck fits in a bathtub',
        answerOne: 'Fel svar 1',
        answerTwo: 'Fel svar 2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 11,
        question: 'How many duck fits in a bathtub',
        answerOne: 'Fel svar1',
        answerTwo: 'Fel svar2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 12,
        question: 'How many duck fits in a bathtub',
        answerOne: 'Fel svar 1',
        answerTwo: 'Fel svar 2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 13,
        question: 'How many duck fits in a bathtub',
        answerOne: 'Fel svar 1',
        answerTwo: 'Fel svar 2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 14,
        question: 'How many duck fits in a bathtub',
        answerOne: 'Fel svar 1',
        answerTwo: 'Fel svar 2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 15,
        question: 'How many duck fits in a bathtub',
        answerOne: 'Fel svar 1',
        answerTwo: 'Fel svar 2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 16,
        question: 'How many duck fits in a bathtub',
        answerOne: 'Fel svar1',
        answerTwo: 'Fel svar2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 17,
        question: 'How many duck fits in a bathtub',
        answerOne: 'Fel svar 1',
        answerTwo: 'Fel svar 2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 18,
        question: 'How many duck fits in a bathtub',
        answerOne: 'Fel svar 1',
        answerTwo: 'Fel svar 2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 19,
        question: 'How many duck fits in a bathtub',
        answerOne: 'Fel svar 1',
        answerTwo: 'Fel svar 2',
        correctAnswer: 'Rätt svar',
    },
    {
        id: 20,
        question: 'How many duck fits in a bathtub',
        answerOne: 'Fel svar 1',
        answerTwo: 'Fel svar 2',
        correctAnswer: 'Rätt svar',
    },
];
export default QuizQuestions;
